FROM php:7.0-fpm

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions

# Set Environment Variables
ENV DEBIAN_FRONTEND=noninteractive

RUN set -eux; \
    sed -i \
    -e 's|deb.debian.org|archive.debian.org|g' \
    -e 's|security.debian.org|archive.debian.org|g' \
    -e '/stretch-updates/d' \
    /etc/apt/sources.list;

###########################################################################
# Install PHP extensions
###########################################################################

ARG PHP_EXTENSIONS=bcmath exif pdo_mysql mysqli pcntl

RUN install-php-extensions @fix_letsencrypt @composer $PHP_EXTENSIONS \
    mcrypt \
    # laradock 5.6 ~ 7.1 之间有此扩展，高版本没有，另外安装需要依赖，所以交给扩展安装
    event \
    sockets \
    intl \
    imagick \
    gd \
    gettext \
    gmp \
    ldap \
    soap \
    pdo_pgsql \
    pgsql \
    redis \
    swoole \
    zip

###########################################################################
# PHP Basic Config
###########################################################################

# 配置参考 https://github.com/thecodingmachine/docker-images-php
# 配置参考 https://github.com/aaPanel/BaoTa/blob/main/script/php_auto.sh

ADD https://curl.se/ca/cacert.pem /usr/local/etc/php/ssl/php-custom-ca.pem
RUN cp $PHP_INI_DIR/php.ini-development $PHP_INI_DIR/php.ini && \
    sed -i 's/^disable_functions/;disable_functions/g' $PHP_INI_DIR/php.ini && \
    sed -i 's/^memory_limit = .*/memory_limit = -1/g' $PHP_INI_DIR/php.ini && \
    sed -i 's/;date.timezone =.*/date.timezone = PRC/g' $PHP_INI_DIR/php.ini && \
    sed -i 's/short_open_tag =.*/short_open_tag = On/g' $PHP_INI_DIR/php.ini && \
    sed -i 's/;cgi.fix_pathinfo=.*/cgi.fix_pathinfo=1/g' $PHP_INI_DIR/php.ini && \
    sed -i 's/display_errors = Off/display_errors = On/g' $PHP_INI_DIR/php.ini && \
    sed -i 's/error_reporting =.*/error_reporting = E_ALL \& \~E_NOTICE/g' $PHP_INI_DIR/php.ini && \
    crtPath="/usr/local/etc/php/ssl/php-custom-ca.pem" && \
    sed -i "s#;openssl.cafile=#openssl.cafile=${crtPath}#" $PHP_INI_DIR/php.ini && \
    sed -i "s#;curl.cainfo =#curl.cainfo = ${crtPath}#" $PHP_INI_DIR/php.ini && \
    sed -i 's/expose_php = On/expose_php = Off/g' $PHP_INI_DIR/php.ini
COPY ./laravel.ini /usr/local/etc/php/conf.d
COPY ./xlaravel.pool.conf /usr/local/etc/php-fpm.d/

###########################################################################
# Set Timezone
###########################################################################

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# php 5.6 以后版本才支持
RUN install-php-extensions xlswriter

