FROM php:8.0-fpm

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions

# Set Environment Variables
ENV DEBIAN_FRONTEND=noninteractive

###########################################################################
# Install PHP extensions
###########################################################################

ARG PHP_EXTENSIONS=bcmath exif pdo_mysql mysqli pcntl

RUN install-php-extensions @fix_letsencrypt @composer $PHP_EXTENSIONS \
    event \
    sockets \
    intl \
    imagick \
    gd \
    gettext \
    gmp \
    ldap \
    soap \
    pdo_pgsql \
    pgsql \
    redis \
    swoole \
    zip

# Download MPL-licensed CA Bundle from curl.se
ADD https://curl.se/ca/cacert.pem /usr/local/etc/php/ssl/php-custom-ca.pem
RUN echo "curl.cainfo = /usr/local/etc/php/ssl/php-custom-ca.pem" > /usr/local/etc/php/conf.d/curl.ini && \
    echo "openssl.cafile = /usr/local/etc/php/ssl/php-custom-ca.pem" > /usr/local/etc/php/conf.d/openssl.ini

###########################################################################
# PHP Basic Config
###########################################################################

COPY ./ini/php8.0.ini /usr/local/etc/php/php.ini
COPY ./laravel.ini /usr/local/etc/php/conf.d
COPY ./xlaravel.pool.conf /usr/local/etc/php-fpm.d/

###########################################################################
# Set Timezone
###########################################################################

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# php 5.6 以后版本才支持
RUN install-php-extensions xlswriter

