FROM php:8.1-fpm

# Set Environment Variables
ENV DEBIAN_FRONTEND=noninteractive

RUN set -eux; \
    # Install the PHP bcmath extention
    docker-php-ext-install bcmath; \
    # Install the PHP pdo_mysql extention
    docker-php-ext-install pdo_mysql mysqli; \
    # Install the PHP exif extention
    docker-php-ext-install exif; \
    # Install the PHP pcntl extention
    docker-php-ext-install pcntl;

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

###########################################################################
# Install PHP extensions
###########################################################################

RUN install-php-extensions @fix_letsencrypt @composer \
    event \
    sockets \
    intl \
    imagick \
    gd \
    gettext \
    gmp \
    ldap \
    soap \
    pdo_pgsql \
    pgsql \
    redis \
    swoole \
    zip

# Download MPL-licensed CA Bundle from curl.se
RUN mkdir -p /usr/local/etc/php/ssl && \
    curl -fsSL https://curl.se/ca/cacert.pem -o /usr/local/etc/php/ssl/php-custom-ca.pem && \
    echo "curl.cainfo = /usr/local/etc/php/ssl/php-custom-ca.pem" > /usr/local/etc/php/conf.d/curl.ini && \
    echo "openssl.cafile = /usr/local/etc/php/ssl/php-custom-ca.pem" > /usr/local/etc/php/conf.d/openssl.ini

###########################################################################
# PHP Basic Config
###########################################################################

COPY ./ini/php8.1.ini /usr/local/etc/php/php.ini
COPY ./laravel.ini /usr/local/etc/php/conf.d
COPY ./xlaravel.pool.conf /usr/local/etc/php-fpm.d/

###########################################################################
# Set Timezone
###########################################################################

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# php 5.6 以后版本才支持
RUN install-php-extensions xlswriter

