FROM php:7.0-fpm

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions

# Set Environment Variables
ENV DEBIAN_FRONTEND=noninteractive

RUN echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99insecure \
    && echo 'Acquire::AllowInsecureRepositories "true";' >> /etc/apt/apt.conf.d/99insecure \
    && echo 'Acquire::AllowDowngradeToInsecureRepositories "true";' >> /etc/apt/apt.conf.d/99insecure \
    && echo 'APT::Get::AllowUnauthenticated "true";' >> /etc/apt/apt.conf.d/99insecure

RUN set -eux; \
    sed -i \
    -e 's|deb.debian.org|archive.debian.org|g' \
    -e 's|security.debian.org|archive.debian.org|g' \
    -e '/stretch-updates/d' \
    /etc/apt/sources.list; \
    apt-get update; \
    apt-get upgrade -y; \
    apt-get install -y --no-install-recommends \
        curl \
        vim \
        git \
        tzdata; \
    rm -rf /var/lib/apt/lists/*

RUN set -eux; \
    # Install the PHP bcmath extention
    docker-php-ext-install bcmath; \
    # Install the PHP pdo_mysql extention
    docker-php-ext-install pdo_mysql mysqli; \
    # Install the PHP exif extention
    docker-php-ext-install exif; \
    # Install the PHP pcntl extention
    docker-php-ext-install pcntl;

###########################################################################
# Install PHP extensions
###########################################################################

RUN install-php-extensions @fix_letsencrypt @composer \
    mcrypt \
    event \
    sockets \
    intl \
    imagick \
    gd \
    gettext \
    gmp \
    ldap \
    soap \
    pdo_pgsql \
    pgsql \
    redis \
    swoole \
    zip

# Download MPL-licensed CA Bundle from curl.se
ADD https://curl.se/ca/cacert.pem /usr/local/etc/php/ssl/php-custom-ca.pem
RUN echo "curl.cainfo = /usr/local/etc/php/ssl/php-custom-ca.pem" > /usr/local/etc/php/conf.d/curl.ini && \
    echo "openssl.cafile = /usr/local/etc/php/ssl/php-custom-ca.pem" > /usr/local/etc/php/conf.d/openssl.ini

###########################################################################
# PHP Basic Config
###########################################################################

COPY ./ini/php7.0.ini /usr/local/etc/php/php.ini
COPY ./laravel.ini /usr/local/etc/php/conf.d
COPY ./xlaravel.pool.conf /usr/local/etc/php-fpm.d/

###########################################################################
# Set Timezone
###########################################################################

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# php 5.6 以后版本才支持
RUN install-php-extensions xlswriter

