ARG LARADOCK_PHP_VERSION=8.5
FROM php:${LARADOCK_PHP_VERSION}-fpm

ARG LARADOCK_PHP_VERSION

# Set Environment Variables
ENV DEBIAN_FRONTEND=noninteractive

# Download MPL-licensed CA Bundle from curl.se
RUN mkdir -p /usr/local/etc/php/ssl && \
    curl -fsSL https://curl.se/ca/cacert.pem -o /usr/local/etc/php/ssl/php-custom-ca.pem && \
    echo "curl.cainfo = /usr/local/etc/php/ssl/php-custom-ca.pem" > /usr/local/etc/php/conf.d/curl.ini && \
    echo "openssl.cafile = /usr/local/etc/php/ssl/php-custom-ca.pem" > /usr/local/etc/php/conf.d/openssl.ini

# Install the PHP bcmath extension
RUN docker-php-ext-install bcmath

# Install for image manipulation
RUN docker-php-ext-install exif

# Install the PHP pcntl extention
RUN docker-php-ext-install pcntl

# Install the PHP pdo_mysql extention
RUN docker-php-ext-install pdo_mysql

# Install the PHP mysqli extention
RUN docker-php-ext-install mysqli

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

###########################################################################
# Install PHP extensions
###########################################################################

RUN install-php-extensions @fix_letsencrypt @composer \
    event \
    sockets \
    intl \
    imagick \
    gd \
    gettext \
    gmp \
    ldap \
    soap \
    pdo_pgsql \
    pgsql \
    redis \
    swoole \
    zip

###########################################################################
# PHP Basic Config
###########################################################################

COPY ./ini/php${LARADOCK_PHP_VERSION}.ini /usr/local/etc/php/php.ini
COPY ./laravel.ini /usr/local/etc/php/conf.d
COPY ./xlaravel.pool.conf /usr/local/etc/php-fpm.d/

###########################################################################
# Set Timezone
###########################################################################

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# php 5.6 以后版本才支持
RUN install-php-extensions xlswriter

