; 来自于宝塔 /www/server/panel/script/php_auto.sh

post_max_size = 50M
upload_max_filesize = 256M
date.timezone = PRC
short_open_tag = On
cgi.fix_pathinfo = 1
max_execution_time = 600
display_errors = On
error_reporting = E_ALL
