; 来自于宝塔 /www/server/panel/script/php_auto.sh

; 上传文件大小配置，来自 https://www.qiqiuyu.com/faq/648/detail
post_max_size = 512M
upload_max_filesize = 512M
memory_limit = 512M

date.timezone = PRC
short_open_tag = On
cgi.fix_pathinfo = 1
max_execution_time = 600
display_errors = On
error_reporting = E_ALL
